### ISSUE TITLE
Missing dependency `immer`

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [dkershner6/use-set-as-state#189]
Does `immer` need to be added to `dependencies` or `peerDependencies`?

**Comment by dkershner6** [comment]
https://github.com/dkershner6/use-set-as-state/blob/50eda4ffc1ab5a7c7f1641eee280ac26360f0d5f/package.json#L67

Any `peerDependency` of a package must be installed as a `dependency` of the consuming project.
